# Generated by Django 5.2.7 on 2026-10-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Lojista',
                'verbose_name_plural': 'Lojistas',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave Pix de Destino')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago / Aprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status da Transação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='pagamentos.lojista', verbose_name='Lojista')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
