# Generated by Django 6.0.4 on 2026-10-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Finalização'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='transacao_valor_positivo'),
        ),
    ]
